[IMP] estate: adding kanban view (Chapter 15) T#71262
andreagidaltig/curso-tecnico-ag pull request #10
Opened 2023-05-15 15:26 UTC by andreagidaltig

- add kanban in estate_property_action - view_mode
- add kanban view with property fields and define conditions to show selling_price and expected_price using t-if
- disable drag and drop

2023-05-15 15:29 UTC, andreagidaltig commented
@edy1192 could you review this PR please?

2023-05-16 15:56 UTC, edy1192 requested changes

2023-05-16 18:47 UTC, andreagidaltig commented on estate/views/estate_property_views.xml
> +                                    <field name="expected_price" />
I tried but the field name isn't showing, as seen in the screenshot (left).
![PR 15](https://github.com/andreagidaltig/curso-tecnico-ag/assets/130611250/814d42d7-822e-403e-8e76-5690c9da8c14)

2023-05-16 21:41 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +                                    <field name="expected_price" />
Oh okay it's better with the text! 😅

2023-05-16 21:41 UTC, edy1192 approved these changes

2023-05-17 16:45 UTC, edy1192 approved these changes

2023-05-17 16:45 UTC, merged