[IMP] estate: restrict access to data (Advanced topics) T#71262
andreagidaltig/curso-tecnico-ag pull request #11
Opened 2023-05-17 21:33 UTC by andreagidaltig

- modifying permissions for accessing to models in ir.model.access.csv
- modifying manifest file to add category key "Real Estate/Brokerage"
- defining groups in security.xml (use of implied_ids)
- adding company_id to estate_property_model (many2one) and to list view in estate_property_view
- defining access rules for agents and companies
- restrict Real Estate-Settings menu just for users in manager group using "groups" attribute

2023-05-17 21:38 UTC, andreagidaltig commented
Hi @edy1192 this PR is ready, could you review it please?

2023-05-18 00:33 UTC, edy1192 requested changes

2023-05-18 00:33 UTC, edy1192 commented on estate/security/security.xml
> +<odoo>
I know that the documentation and exercises don't say anything about splitting models by file but we normally split it into one file per model. As follows:

- `res.groups` records go to a `res_groups_security.xml` file.
- `ir.rule` records go to an `ir_rule_security.xml` file.

Could you please apply it?

2023-05-18 00:33 UTC, edy1192 commented on estate/security/security.xml
> +        <field name="implied_ids" eval="[ref('estate_group_user')]" />
Use `Command`, please.

2023-05-18 00:33 UTC, edy1192 commented on estate/views/estate_menus.xml
> +        <menuitem id="estate_settings_menu" name="Settings" groups="estate_group_manager">
Normally we use this notation to call the record's module: `module_name.xml_id`

```suggestion
        <menuitem id="estate_settings_menu" name="Settings" groups="estate.estate_group_manager">
```

2023-05-18 00:33 UTC, edy1192 commented on estate/security/security.xml
> +        <field name="global" eval="True" />
Why global?

2023-05-18 00:33 UTC, edy1192 commented on estate/security/security.xml
> +        <field name="groups" eval="[Command.link(ref('estate_group_user'))]" />
```suggestion
        <field name="groups" eval="[Command.link(ref('estate.estate_group_user'))]" />
```

2023-05-18 19:07 UTC, edy1192 requested changes

2023-05-18 19:07 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +        <field name="global" eval="True" />
We must see if this is a global rule or a group rule. Because the exercise says:

> **All agents** can see all companies, which is not desirable, add the record rule restricting this behavior.

I think it refers to the group  `estate_group_user`.

2023-05-18 19:07 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +    <record id="property_restricted_company_rule" model="ir.rule">
```suggestion
    <record id="estate_property_restricted_company_rule" model="ir.rule">
```

2023-05-18 22:34 UTC, edy1192 requested changes

2023-05-18 22:34 UTC, edy1192 commented on estate/security/res_groups_security.xml
> +        <field name="implied_ids" eval="[Command.link(ref('estate.estate_group_user'))]" />
Add users to this group

Example:  https://github.com/odoo/odoo/blob/16.0/addons/hr/security/hr_security.xml#L20

2023-05-18 22:34 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +
Please do the admin rule for` estate.property` model.

2023-05-19 16:49 UTC, edy1192 requested changes

2023-05-19 16:49 UTC, edy1192 commented on estate/security/res_groups_security.xml
> +        <field name="users" eval="[(4, ref('base.user_root')), (4, ref('base.user_admin'))]" />
Please, use Command for this.

2023-05-19 16:49 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +        </field>
```suggestion
        <field name="name">The admin can create, view and modify any property.</field>
```

2023-05-19 16:49 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +        </field>
```suggestion
        <field name="domain_force">[(1, '=', 1)]</field>
```

2023-05-19 16:49 UTC, edy1192 commented on estate/security/ir_rule_security.xml
> +        </field>
```suggestion
        <field name="domain_force">[('company_id', 'in', company_ids)]</field>
```

2023-05-19 17:49 UTC, edy1192 approved these changes

2023-05-19 17:50 UTC, merged