[IMP] estate: adding master and demo data (Advanced topics) T#71262
andreagidaltig/curso-tecnico-ag pull request #13
Opened 2023-05-19 17:55 UTC by andreagidaltig

- add demo directory and demo files for estate.property and estate.property.offer models
- link offers to a partner_id (review metadata to get the xml.id)
- link offers in offers demo file to properties in properties demo file using ref attribute and also use Command.create into the properties demo file to add offers
- add data directory and estate.property.type.csv to define the property types using ref attribute

2023-05-19 18:43 UTC, edy1192 requested changes

2023-05-19 18:43 UTC, edy1192 commented on estate/__manifest__.py
> +        "data/estate.property.type.csv",
1. Normally we use XML files to create module data. But I suppose the documentation adds it with a CSV file for practicing purposes. 
2. This file should be named with `_`

```suggestion
        "data/estate_property_type_data.csv",
```

Please, check the guidelines for [file naming ](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming) and apply it to these files.

2023-05-19 18:43 UTC, edy1192 commented on estate/data/estate.property.type.csv
> +property_type_1,Residential
Please use meaningful names for ids. Something like this 
```suggestion
residential_property_type,Residential
```

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +    <record id="property_demo_1" model="estate.property">
Please check the guidelines for naming demo records https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#254demo-records

This should be something like:

```suggestion
    <record id="big_villa_property_demo" model="estate.property">
```
Please, apply this suggestion to **all** the xml_ids in **all** the XML files.

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="garden">True</field>
True and False are code sentences so please, use eval.

https://www.odoo.com/documentation/16.0/es/developer/tutorials/define_module_data.html#eval

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +
```suggestion
```

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="selling_price">0</field>
What happens if you don't set a value for this field? The exercise doesn't say anything about this field.

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="garage">False</field>
Use eval, please.

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property_offer.xml
> +        <field name="date_deadline" eval="datetime.now().date() + relativedelta(days=14)" />
Why this `+ relativedelta(days=14)`?

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +                'property_id': 'property_demo_3',
You don't need to add the `property_id` field as the `Command.create` sentence associates it automatically, detecting that you are creating records for the `o2m` field of the relationship. Please, apply this suggestion to the same occurrences below.

2023-05-19 18:43 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +                'partner_id': 14,
Please don't add the database ID directly, this is not right because if by chance the IDs in the database change you will have a wrong data in this relationship. You can use the `ref` command here. Please, apply this suggestion to the same occurrences below.

Like this:
```suggestion
                'partner_id': ref('base.partner_id'),
```

2023-05-19 20:48 UTC, andreagidaltig commented on estate/demo/demo_data_estate_property_offer.xml
> +        <field name="date_deadline" eval="datetime.now().date() + relativedelta(days=14)" />
Because I tried to do something similar to _compute_date_deadline method in estate property offer model, there I used validity value.

2023-05-19 22:05 UTC, edy1192 commented on estate/demo/demo_data_estate_property_offer.xml
> +        <field name="date_deadline" eval="datetime.now().date() + relativedelta(days=14)" />
But the exercise says:

> The offers you added should always be in a date relative to the installation of the module.

I understand that is set the date with today's value or now in your case.

2023-05-22 02:59 UTC, edy1192 requested changes

2023-05-22 02:59 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="selling_price">0</field>
Pending.

2023-05-22 02:59 UTC, edy1192 commented on estate/__manifest__.py
> +        "demo/demo_data_estate_property_offer.xml",
Please rename the files. Check guidelines for file naming https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#15file-naming the word "demo" / "data" / "views" is a suffix. And the word `data` is a suffix for files in the "data" section.

```suggestion
        "demo/estate_property_demo.xml",
        "demo/estate_property_offer_demo.xml",
```

2023-05-22 02:59 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="name">Trailer home</field>
```suggestion
    <record id="trailer_home_property_demo" model="estate.property">
        <field name="name">Trailer Home</field>
```

2023-05-22 02:59 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="description">Home in a trailer park</field>
```suggestion
        <field name="description">Home in a trailer park.</field>
```

2023-05-22 02:59 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="description">A nice and big villa</field>
```suggestion
        <field name="description">A nice and big villa.</field>
```

2023-05-22 02:59 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="description">A small but nice and cozy villa</field>
```suggestion
        <field name="description">A small but nice and cozy villa.</field>
```

2023-05-22 13:29 UTC, andreagidaltig commented on estate/demo/demo_data_estate_property.xml
> +        <field name="selling_price">0</field>
I forgot to check it...
I removed those lines and it seems to work fine, I'm trying to remember that somewhere I read that the default value for float fields is 0 but maybe I'm lying.

2023-05-22 18:48 UTC, edy1192 requested changes

2023-05-22 18:48 UTC, edy1192 commented on estate/demo/estate_property_offer_demo.xml
> +    </function>
The exercise says:

> Validate one of the demo data offers by using the “Accept Offer” button. Refuse the others.

Please refuse the `trailer_home_property_offer_demo` offer.

2023-05-22 18:48 UTC, edy1192 commented on estate/demo/demo_data_estate_property.xml
> +        <field name="selling_price">0</field>
🤣 You're not lying. That's true, 0 is the default value for integer and float fields.

2023-05-22 19:10 UTC, edy1192 approved these changes

2023-05-22 19:10 UTC, edy1192 approved these changes

2023-05-22 19:10 UTC, merged