[IMP] estate: writing unit tests for estate module (Advanced topics) #71262
andreagidaltig/curso-tecnico-ag pull request #14
Opened 2023-05-23 22:07 UTC by andreagidaltig

- update the code so no one can create an offer for a sold property and sell a property with no accepted offers on it.
- check if you cannot add an offer to a property that has already been sold.
- check if you cannot sell a property without accepting an offer.
- check if the status property changes when a property is sold.
- using Form to emulate form view actions
- use Form to all the tests

2023-05-23 22:38 UTC, andreagidaltig commented
Hi @edy1192 could you check this PR please?

2023-05-23 23:51 UTC, edy1192 requested changes

2023-05-23 23:51 UTC, edy1192 commented on estate/models/estate_property.py
> +            if record.status in ["new", "offer_received"]:
Why don't you check if there are offers accepted in the `offer_ids` field? Can I have a property with an accepted offer and have the property with the status "new"?

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/common.py
> +class EstatePropertyCommon(TransactionCase):
Use the module name, please. Because this can be used by all unit tests of any model. 

```suggestion
class EstateTransactionCase(TransactionCase):
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +@tagged("post_install", "-at_install")
Please add a tag to use in the `--test-tags` command. Check Special tags https://www.odoo.com/documentation/16.0/developer/reference/backend/testing.html#special-tags the `standard`.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +class EstatePropertyTestCase(EstatePropertyCommon):
Normally we named the class equal to the file's name.

 ```suggestion
class TestEstateProperty(EstatePropertyCommon):
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def test_001_sell_property_whithout_offers(self):
```suggestion
    def test_001_sell_property_without_accepted_offers(self):
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def test_002_offer_creation_to_sold_property(self):
```suggestion
    def test_002_create_offer_for_sold_property(self):
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        estate_property_form.status = "sold"
Please use the action to sell the property.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +                    offer.date_deadline = fields.Date.add(fields.Date.today(), days=offer.validity)
This is a computed field that depends on the `creation_date` and `validity` fields, it should be computed when you set the validity so please don't assign a value here.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        estate_property_form.status = "offer_received"
Setting the status here is unnecessary because it's assigned when you create the offer.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        self.assertEqual(estate_property.status, "sold", "The property status wasn't update.")
The status property is `sold` here? It should not be because raising a raise does not complete the process. But in unit tests, a parameter must be added to the `assertRaisesRegex` so that it detects the error and does not perform the operation.

Check this line https://github.com/odoo/odoo/blob/16.0/addons/l10n_latam_check/tests/test_third_party_checks.py#L68

Then you can check if the status changed or is still in "new"

Also, please fix the message: It should be `The property status wasn't updated.`

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +                offer.date_deadline = fields.Date.add(fields.Date.today(), days=offer.validity)
Same as above, don't do this.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        self.assertEqual(estate_property.status, "sold", "The property status wasn't update.")
```suggestion
        self.assertEqual(estate_property.status, "sold", "The property status wasn't updated.")
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        self.assertEqual(estate_property_form.garden_area, 10, "The garden area wasn't updated.")
```suggestion
        self.assertEqual(estate_property_form.garden_area, 10, "The garden area has not been updated.")
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        self.assertEqual(estate_property_form.garden_orientation, "north", "The garden orientation wasn't updated.")
```suggestion
        self.assertEqual(estate_property_form.garden_orientation, "north", "The orientation of the garden has not been updated.")
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        self.assertEqual(estate_property.garden_orientation, "north", "The garden orientation wasn't updated.")
The message at the end of `assert` method is shown when the assert fails. In this case, you're checking that the values are still the same, so the message should be: "The value has been updated."

```suggestion
        self.assertEqual(estate_property.garden_area, 10, "The garden area has been updated.")
        self.assertEqual(estate_property.garden_orientation, "north", "The garden orientation has been updated.")
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +class EstatePropertyTagCase(TransactionCase):
```suggestion
class TestEstatePropertyTag(TransactionCase):
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +@tagged("post_install", "-at_install")
Add tag please.

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +        super(EstatePropertyTagCase, cls).setUpClass()
You're not using the setup method so it's not necessary. 

```suggestion
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +        estate_property_form = Form(self.env["estate.property.tag"])
```suggestion
        estate_property_tag_form = Form(self.env["estate.property.tag"])
```

2023-05-23 23:51 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +            estate_property_form_2.save()
Check that you can create a tag with a different name, please.

2023-05-24 01:58 UTC, andreagidaltig commented on estate/tests/test_estate_property.py
> +        estate_property_form.status = "sold"
If I do this I will not be able to check the Raise Regex, this is because there are no offers yet and that exception is raised first.

2023-05-24 14:35 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +        estate_property_form.status = "sold"
I got it, so first add an offer, sell the property (using the action) then try to add a new offer (which is what you're checking here).

2023-05-24 15:20 UTC, andreagidaltig commented on estate/models/estate_property.py
> +            if record.status in ["new", "offer_received"]:
I don't know if I got it but when an offer is accepted the status of the offer changes and also the status of the property changes to offer_accepted, it happens in the same method (action_accept_offer)

2023-05-24 21:48 UTC, edy1192 requested changes

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +@tagged("post_install", "-at_install", "estate_property")
The order is:

```suggestion
@tagged("estate_property", "post_install", "-at_install")
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def test_001_sell_property_whithout_accepted_offers(self):
Pending https://github.com/andreagidaltig/curso-tecnico-ag/pull/14#discussion_r1203147715

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def _test_002_create_offer_for_sold_property(self):
```suggestion
    def test_002_create_offer_for_sold_property(self):
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def _test_003_sell_property_whit_offer_received(self):
```suggestion
    def test_003_sell_property_with_offer_received(self):
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +    def _test_004_uncheck_garden(self):
```suggestion
    def test_004_uncheck_garden(self):
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +            estate_property_form.garden_orientation, "north", "The orientation of the garden has not been updated."
```suggestion
            estate_property_form.garden_orientation, "north", "The orientation of the garden has not been updated.",
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +            estate_property.garden_orientation, "north", "The orientation of the garden has been updated."
```suggestion
            estate_property.garden_orientation, "north", "The orientation of the garden has been updated.",
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property_tag.py
> +@tagged("post_install", "-at_install", "estate_property_tag")
```suggestion
@tagged("estate_property_tag", "post_install", "-at_install")
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/common.py
> +        estate_property_form.status = "new"
The status default value is "new"

```suggestion
```

2023-05-24 21:48 UTC, edy1192 commented on estate/tests/test_estate_property.py
> +            estate_property.action_sold_property()
You already checked this in `test_001...` Please, don't sell the property before adding an offer. 

```suggestion
```

2023-05-25 00:02 UTC, edy1192 requested changes

2023-05-25 15:26 UTC, edy1192 approved these changes

2023-05-25 15:26 UTC, merged