[IMP] estate: build PDF reports (Advanced topics) T#71262
andreagidaltig/curso-tecnico-ag pull request #15
Opened 2023-05-26 01:57 UTC by andreagidaltig

- add the report directory and files for report actions (this activates the button to print) and templates
- split the templates in 3 files one for common templates, one for invoice template and one for the template of offers template and the template of salesman properties
- change the external_layout to add header with data from company and configure the layout in the interface - general settings
- add the files to manifest
![PR pdfs 3](https://github.com/andreagidaltig/curso-tecnico-ag/assets/130611250/894ee22e-4c8a-43b1-b91b-fc034f396390)
![PR pdfs 4](https://github.com/andreagidaltig/curso-tecnico-ag/assets/130611250/2a60a4b1-f24e-481f-8aff-93b5c3ee1936)
![PR pdfs](https://github.com/andreagidaltig/curso-tecnico-ag/assets/130611250/e98c971a-4317-494b-94ac-840ffc66310a)
![PR pdfs 2](https://github.com/andreagidaltig/curso-tecnico-ag/assets/130611250/812a77f3-c131-479d-8f30-c4700f47205c)

2023-05-26 16:42 UTC, andreagidaltig commented
Hi @edy1192 could you check this PR please?

2023-05-26 21:15 UTC, edy1192 requested changes

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_templates.xml
> +    <template id="report_property_offers">
```suggestion
    <template id="estate_property_report">
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_reports.xml
> +        <field name="print_report_name">'Estate Property Offers - %s' % (object.name or 'Offer')</field>
```suggestion
        <field name="print_report_name">'Estate Property - %s' % (object.name or 'Property Report')</field>
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_reports.xml
> +    <record id="action_report_salesman_properties" model="ir.actions.report">
```suggestion
    <record id="salesperson_properties_action_report" model="ir.actions.report">
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_reports.xml
> +        <field name="name">Salesman Real Estate Properties</field>
```suggestion
        <field name="name">Salesperson Properties</field>
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_templates.xml
> +    <template id="report_salesman_properties">
```suggestion
    <template id="salesperson_properties_report">
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_reports.xml
> +        <field name="print_report_name">'Salesman Real Estate Properties - %s' % (object.name or 'Salesman')</field>
```suggestion
        <field name="print_report_name">'Salesperson Properties - %s' % (object.name or 'Salesperson Properties')</field>
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_templates.xml
> +                                <strong>Salesman:</strong>
```suggestion
                                <strong>Salesperson:</strong>
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_common_templates.xml
> +    <template id="offers_table">
```suggestion
    <template id="offers_table_template">
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_templates.xml
> +        <t t-foreach="docs" t-as="salesman">
Replace `salesman` with `salesperson` in all the files, please.
```suggestion
        <t t-foreach="docs" t-as="salesperson">
```

2023-05-26 21:15 UTC, edy1192 commented on estate/report/estate_property_templates.xml
> +                        <t t-foreach="properties" t-as="property">
Could you try this?
```suggestion
                        <t t-foreach="salesperson.property_ids" t-as="property">
```

2023-05-29 15:49 UTC, edy1192 requested changes

2023-05-29 15:49 UTC, edy1192 commented on estate/reports/estate_property_invoice_templates.xml
> +    <template id="invoice_property" inherit_id="estate.estate_property_report">
```suggestion
    <template id="invoice_property_template" inherit_id="estate_property_report">
```
I recently learned that if the xml_id you're referring to is in the same module, you don't need to add the module name because it's redundant. Before if it was necessary and I got used to it, my apologies for having asked you before to add the name of the module. You can leave it like that or change it, but keep that in mind for the future.

2023-05-29 15:49 UTC, edy1192 commented on estate/reports/estate_property_invoice_templates.xml
> +            <div t-if="status=='sold'">
I usually try to avoid `t-set` unless is necessary.

```suggestion
            <div t-if="property.status=='sold'">
```

2023-05-30 16:26 UTC, edy1192 approved these changes

2023-05-30 16:26 UTC, merged