[IMP] estate: Permission specifications to the base.group_user and new fields in RealEstate module T#71262
andreagidaltig/curso-tecnico-ag pull request #2
Opened 2023-04-25 23:45 UTC by AndreaGidaltiG

- Permissions specifications in ir.model.access.csv file
- New menu with menuitem tags (3 levels)
- New fields (activate and status) and specifications for them

2023-04-25 23:46 UTC, AndreaGidaltiG commented
@edy1192 could you check this PR please?

2023-04-26 00:10 UTC, edy1192 commented
Hi @AndreaGidaltiG you need to rebase this PR and delete the first commit one with [ADD] tag.

You need to follow these steps:

1. `git rebase -i origin/16.0`
2. There will be the list of commits of your branch and they will have the word `pick` at the beginning. Find the commit with the `[ADD]` tag and change the word `pick` to `drop` (don't change anything else).
3. Then you do `:wq` to save and exit that editor. Maybe it gives you conflicts, you must resolve them, you can ask Alberto or Deivis for help if you need it.
4. Then you switch to the stable branch: `git checkout 16.0`
5. You update the stable branch: `git pull origin 16.0`
6. Go back to your branch: `git checkout -`
7. You rebase again: `git rebase -i origin/16.0` (if there are conflicts you must resolve them).

2023-04-26 21:17 UTC, AndreaGidaltiG commented
@deivislaya could you check this PR please?

2023-04-26 21:50 UTC, deivislaya commented on README.rst
> +# curso-tecnico-ag
The file readme can be something more structured, from the beginning, for example

```
Real Estate module (`estate`)
=============================


Real Estate module for technical training Odoo.
```

2023-04-26 21:50 UTC, deivislaya commented on estate/security/ir.model.access.csv
> +access_estate_property,access_estate_property,model_estate_property,base.group_user,1,1,1,1
FIx end of file

2023-04-26 22:05 UTC, deivislaya commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action"  name="Action 1"/>
```suggestion
            <menuitem id="estate_model_menu_action" action="estate_property_action"  name="Properties"/>
```


![Chapter-6-Finally-Some-UI-To-Play-With-—-Odoo-16-0-documentation](https://user-images.githubusercontent.com/5775695/234713223-d254333d-1859-4bee-b8f2-d770adab205b.png)

2023-04-26 22:29 UTC, deivislaya commented on estate/models/estate_property.py
> +        copy=False,
```suggestion
    status = fields.Selection(
        selection=[
            ("new", "New"),
            ("offer_received", "Offer Received"),
            ("offer_accepted", "Offer Accepted"),
            ("sold", "Sold"),
            ("canceled", "Canceled"),
        ],
        default="new",
        copy=False,
    )
```

Please, always, run pre-commit-vauxoo -t all. 

The exercise says:

 It must be **required**, should not be copied and should have its default value set to ‘New’.

2023-04-27 01:17 UTC, AndreaGidaltiG commented on estate/security/ir.model.access.csv
> +access_estate_property,access_estate_property,model_estate_property,base.group_user,1,1,1,1
Could you explain me what you mean? I didn't get it @deivislaya

2023-04-27 01:21 UTC, AndreaGidaltiG commented
@deivislaya could you check this PR again please? 
I've already made the changes and just have one doubt about "the end of file".

2023-04-28 01:01 UTC, deivislaya commented on estate/security/ir.model.access.csv
> +access_estate_property,access_estate_property,model_estate_property,base.group_user,1,1,1,1
An error was displayed at the end of the line, it is no longer displayed.

2023-05-02 15:53 UTC, edy1192 requested changes

2023-05-02 15:53 UTC, edy1192 commented on README.rst
> +Real Estate module for technical training Odoo.
```suggestion
Real Estate module for Odoo technical training.
```

2023-05-02 15:53 UTC, edy1192 commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action" name="Properties" />
```suggestion
            <menuitem id="estate_model_menu_action" action="estate_property_action" />
```

Adding the `name` attribute is unnecessary in this case, because the action already has a name assigned `Properties` so the menu will take that name by default. Actually, the documentation says so

![image](https://user-images.githubusercontent.com/11479473/235715027-ab2c4c2c-cb4e-4d65-a2da-06331e231127.png)

2023-05-02 15:53 UTC, edy1192 commented on estate/views/estate_menus.xml
> +        <menuitem id="estate_first_level_menu" name="Advertisements">
The correct thing is to associate the `id` with what we are creating. In this case, the application may have many menus and it is not right to call them with a number, it is not intuitive.

You can review the guidelines for these cases:
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#252security-view-and-action
Something like this:

```suggestion
        <menuitem id="estate_advertisement_menu" name="Advertisements">
```

Apply this suggestion to all the ids in this file, please.

2023-05-02 17:15 UTC, edy1192 requested changes

2023-05-02 17:15 UTC, edy1192 commented on estate/views/estate_menus.xml
> +            <menuitem id="estate_model_menu_action" action="estate_property_action"/>
Sorry, You don't apply my suggestion to all the ids as I said here https://github.com/andreagidaltig/curso-tecnico-ag/pull/2#discussion_r1182739809

```suggestion
            <menuitem id="estate_property_menu" action="estate_property_action"/>
```

Also, you need to run pre-commit-vauxoo -t all to fix the format of the file.

This should be:

```suggestion
            <menuitem id="estate_model_menu_action" action="estate_property_action" />
```

2023-05-02 18:27 UTC, andreagidaltig commented
@edy1192 could you review this PR again, please?

2023-05-02 18:33 UTC, merged