[IMP] estate: adding new models and linking them with Many2one, Many2many and One2many
andreagidaltig/curso-tecnico-ag pull request #3
Opened 2023-05-02 15:19 UTC by andreagidaltig

- Add model, views, menu option and access permissions to estate.property.type
- Add model, views, menu option and access permissions to estate.property.tag
- Add model and access permissions to estate.property.offer
- Add new fields and notebook pages to estate_property_view to show data from linked models
- init and manifest were modified to apply mentioned changes
Chapter 8: https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/08_relations.html

2023-05-02 15:20 UTC, andreagidaltig commented
@edy1192 could you check this PR please?

2023-05-02 17:03 UTC, edy1192 requested changes

2023-05-02 18:28 UTC, andreagidaltig commented
@edy1192 could you review this PR again, please?

2023-05-03 03:29 UTC, andreagidaltig commented on estate/models/estate_property.py
> +    offer_ids = fields.One2many("estate.property.offer", "property_id", string="Offers")
@edy1192 how many attributes should the function have to put the trailing comma?
I used the comma with 3 or 4 attributes and in selection fields, but I don't know what in casses with less attributes, for example in property_type_id

2023-05-03 15:56 UTC, edy1192 commented on estate/views/estate_menus.xml
> +        </menuitem>
Please improve the id's name. Remember that the ids must be unique and intuitive. We don't usually use words like: `model` in the name of an id.

```suggestion
        <menuitem id="estate_settings_menu" name="Settings">
            <menuitem id="estate_property_type_menu" action="estate_property_type_action" />
            <menuitem id="estate_property_tag_menu" action="estate_property_tag_action" />
        </menuitem>
```

2023-05-03 15:56 UTC, edy1192 commented on estate/models/estate_property.py
> +    offer_ids = fields.One2many("estate.property.offer", "property_id", string="Offers")
Hi @andreagidaltig There are no established criteria as such. 

What I usually follow to add a comma at the end is:
- If the field is a selection.
- If it has the help attribute.
- If the attributes it has do not fit on the same line (there are more than 119 characters).

2023-05-03 16:04 UTC, edy1192 commented
Hi @andreagidaltig there are some pending comments, please check the hidden conversations.

![image](https://user-images.githubusercontent.com/11479473/235973888-6d8c4a82-c84a-439f-85c4-c422a1c16ab0.png)

Regards.

2023-05-03 18:22 UTC, edy1192 requested changes

2023-05-03 18:22 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +        <field name="name">estate.property.tree</field>
```suggestion
        <field name="name">estate.property.list</field>
```

2023-05-03 18:22 UTC, edy1192 commented on estate/views/estate_property_views.xml
> +                                <field name="property_type_id" />
This field is duplicated on line 33, please remove it here.

2023-05-03 21:28 UTC, edy1192 approved these changes

2023-05-03 21:28 UTC, merged