[IMP] estate: adding business logic to CRUD methods with python inheritance and creating estate account module to use account.move (chapters 13 & 14) T#71262
andreagidaltig/curso-tecnico-ag pull request #9
Opened 2023-05-15 15:21 UTC by andreagidaltig

- prevent deletion of properties if the status is not new or canceled using api.ondelete
- set status to offer_received when creating new offer using api.model - create
- validate that a new offer is accepted only if the price is higher than the maximum price of existing offers
- inherit res.users and define one2many with salesman_id
- inherit res_users_views add notebook page, modify the manifest file and import res.user model in init
- add files for estate account module, inherit estate.property model
- overwrite action_sold_property and add invoice creation

2023-05-15 15:22 UTC, andreagidaltig commented
@edy1192  could you check this PR please?

2023-05-15 23:55 UTC, edy1192 requested changes

2023-05-15 23:55 UTC, edy1192 commented on estate/models/estate_property.py
> +    def _unlink_if_property_status_not_new_canceled(self):
This should be named `_unlink_if_<condition>` or `_unlink_except_<not_condition>` according to documentation.

```suggestion
    def _unlink_if_new_canceled(self):
```

2023-05-15 23:55 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +        return super().create(vals)
You can do here the validation of the price and then set the status in vals.
```suggestion
        property = self.env["estate.property"].browse(vals["property_id"])
        max_price = max(property.offer_ids.mapped("price"))
        if max_price and float_compare(vals["price"], max_price, precision_digits=2) == -1:
            raise UserError("The offer price cannot be lower than %.2f" % max_price)
        vals.update({"status":  "offer_received"})
        return super().create(vals)
```

2023-05-15 23:55 UTC, edy1192 commented on estate/models/res_users.py
> +class ResUser(models.Model):
```suggestion
class ResUsers(models.Model):
```

2023-05-15 23:55 UTC, edy1192 commented on estate/models/res_users.py
> +        domain="[('status', 'in', ['new', 'offer_received'])]",
```suggestion
        domain="[('status', 'in', ['new', 'offer_received'])]",
        string="Users",
```

2023-05-15 23:55 UTC, edy1192 commented on estate/views/res_users_views.xml
> +    <data>
This is not necessary.

2023-05-15 23:55 UTC, edy1192 commented on estate/views/res_users_views.xml
> +        <record id="res_users_view_form" model="ir.ui.view">
In inherited views, we use the same xml_id as the original view.

```suggestion
        <record id="view_users_form" model="ir.ui.view">
```

2023-05-15 23:55 UTC, edy1192 commented on estate/views/res_users_views.xml
> +            <field name="name">res.users.view.form.inherit.estate</field>
With the word `inherited` it is already known that you are inheriting it and since you are already in the estate module.

```suggestion
            <field name="name">res.users.view.form.inherited</field>
```

2023-05-15 23:55 UTC, edy1192 commented on estate/views/res_users_views.xml
> +                </notebook>
Please try to be more specific with the XPath. Something like this

```suggestion
                <page name="preferences" position="after">
                    <page string="Real Estate Properties">
                        <field name="property_ids" />
                    </page>
                </page>
```

2023-05-15 23:55 UTC, edy1192 commented on estate_account/README.rst
> +# Real Estate Account
Add a description, please.

2023-05-15 23:55 UTC, edy1192 commented on estate_account/models/estate_property.py
> +                            "price_unit": self.selling_price,
The exercise says: 

> an additional 100.00 from administrative fees

2023-05-15 23:55 UTC, edy1192 commented on estate_account/models/estate_property.py
> +        return super().action_sold_property()
When we inherit methods from buttons or that perform validations, it is recommended to first call super. For example, if at the time of selling a property, it does not meet this [validation](https://github.com/andreagidaltig/curso-tecnico-ag/blob/16.0/estate/models/estate_property.py#L110) your code will have already created the invoice and that is not correct. On the other hand, if you call the super first, the raise is executed and the invoice is no longer created.

2023-05-15 23:55 UTC, edy1192 commented on estate_account/models/estate_property.py
> +
```suggestion
```

2023-05-15 23:55 UTC, edy1192 commented on estate_account/__manifest__.py
> +        "base",
This is not necessary because the estate module already depends on the base module. 

```suggestion
```

2023-05-15 23:55 UTC, edy1192 commented on estate_account/__manifest__.py
> +        "account",
```suggestion
        "account",
        "estate",
```

2023-05-15 23:55 UTC, edy1192 commented on estate/models/estate_property.py
> +    def check_offer_price(self, new_price):
I think this method should not be here but in estate_property_offer model.

2023-05-16 18:56 UTC, andreagidaltig commented on estate/models/estate_property_offer.py
> +        return super().create(vals)
I changed "property" to "actual_property" in the next PR (my mistake) because the pre-commit give me this error "shadows built in name" and I didn't notice.

2023-05-16 21:35 UTC, edy1192 requested changes

2023-05-16 21:35 UTC, edy1192 commented on estate/views/res_users_views.xml
> +<record id="view_users_form" model="ir.ui.view">
I meant that the data node is not necessary but you must add these nodes
```

<?xml version="1.0" encoding="utf-8" ?>
<odoo>
....
</odoo>
```

2023-05-16 21:35 UTC, edy1192 commented on estate_account/README.rst
> +The Real Estate Account module inherits functionality from real estate module.
```suggestion
The Real Estate Account module inherits functionality from the estate module.
```

2023-05-16 21:35 UTC, edy1192 commented on estate/models/estate_property_offer.py
> +        return super().create(vals)
Sorry, I was thinking this was the `estate_property` model, so updating the `vals` variable is not okay here, because it's not the property status but the property offer.

```suggestion
        actual_property = self.env["estate.property"].browse(vals["property_id"])
        max_price = max(actual_property.offer_ids.mapped("price"))
        if max_price and float_compare(vals["price"], max_price, precision_digits=2) == -1:
            raise UserError("The offer price cannot be lower than %.2f" % max_price)
        actual_property.status = "offer_received"
        return super().create(vals)
```

2023-05-16 23:42 UTC, edy1192 approved these changes

2023-05-16 23:42 UTC, merged